### ISSUE TITLE
report_ids, argument required

### ISSUE THREAD

**Issue by bighans** [fasteddy516/CircuitPython_JoystickXL#3]
Hi Fasteddy,

Due to other errors, I have done a complete new install on an "unpexcted maker" board. I have added a MCP3008 as this is used in the sample code. Note that only Beta.0 is available for board I am using, albeit your instructions stated that Beta.1 is required.

However, on boot I get the following errors. Please help.

-----------
Adafruit CircuitPython 7.0.0-beta.0 on 2021-08-24; FeatherS2 with ESP32S2
boot.py output:
+ Enabled JoystickXL 0.4.0 with 8 axes, 128 buttons and 4 hats for a total of 26 report bytes.
Traceback (most recent call last):
  File "boot.py", line 8, in <module>
  File "C:\Users\Edward\Source\Repos\fasteddy516\CircuitPython_JoystickXL\joystick_xl\hid.py", line 147, in create_joystick
TypeError: 'report_ids' argument required

-----------

**Comment by fasteddy516** [comment]
Sorry about the confusion - the API for custom USB devices changed as of CircuitPython 7.0.0-beta.0, but the beta.0 release [contains a bug that prevents it from working at all](https://github.com/adafruit/circuitpython/issues/5213).  That bug has been fixed, but there has not been an official beta.1 release yet, so in the meantime you'll have to use the "Absolute Newest" build of CircuitPython for your board, along with JoystickXL 0.4.1, which I just posted.

To get the "Absolute Newest" CircuitPython build, go to the [downloads section of circuitpython.org](https://circuitpython.org/downloads), select your board, click the `Browse S3` link in the `Absolute Newest` section, then select your desired language from the listing that appears.  From here, you can either just try the newest build from the top, or do a search for `20210824-da320c3`, which is the build where the USB bug was fixed.

If you continue to have issues with JoystickXL 0.4.1 and one of the newer builds of CircuitPython, please let me know.

**Comment by bighans** [comment]
Result! I used the 20210824-da320c3 version which seems fine. Now I can back to the original project which is a helicopter joystick.

Just to have mentioned this:

Now I just need to raise an issue on the adafruit MCP 3008 library as the SPI clock needs to be reduced as there is some noise on the readings. I will go back to the ADS1015 as it has a better resolution around the center points.

Adafruit CircuitPython 7.0.0-beta.0-114-g5a4029059 on 2021-08-28; FeatherS2 with ESP32S2
Board ID:unexpectedmaker_feathers2
boot.py output:
+ Enabled JoystickXL 0.4.1 with 3 axes, 0 buttons and 0 hats for a total of 3 report bytes.
